[env]
LISTEN_PORT = "9876"
INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_ORG = "co2"
INFLUXDB_TOKEN = "jsDmEJty4S0gtPyPCbK2QGUIaN94pEd_wN61qj19g4VyaV95tjqAVNiVVfxxDsyPoq9XW9zAJY9K8K0HJLJC-g=="
INFLUXDB_BUCKET = "co2"
